name: Update Language Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Runs weekly

jobs:
  update-readme:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate language stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          filename: github-metrics.svg
          base: header, languages
          config_timezone: Europe/Stockholm
